sendmail:
    path:     /dashbord/cma/sendmail.php_name=home
    defaults: { _controller: CmaBundle:Sendmail:index }

sendmail_redirection:
    path:     /dashbord/cma/sendmail.php_name=redirection
    defaults: { _controller: CmaBundle:Sendmail:redirection }

sendmail_send:
    path:     /dashbord/cma/sendmail.php_name=sendmail
    defaults: { _controller: CmaBundle:Sendmail:sendMail }
    methods: POST

