<?php

namespace Cma\CmaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AproposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
}
