<?php

namespace Cma\CmaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceImgRepository extends EntityRepository
{
}
