<?php

namespace Cma\CmaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialRepository extends EntityRepository
{
}
