cma_user:
    resource: "@CmaUserBundle/Resources/config/routing.yml"
    prefix:   /

cma:
    resource: "@CmaBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

 
 